apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: metrics
	department: engineering
  ports:
  -  protocol: TCP
     port: 80 # port of worker node
	 targetPort: 50000 #port of pod
     nodePort: 30001 #port of network access in browser